/**
 * Input normalisation shared by every form on the site.
 *
 * These run inside the Zod schemas, which both the browser and the API routes
 * parse with — so a value is cleaned before it is validated, and cleaned again
 * server-side regardless of what the client did. Nothing here is an HTML
 * escaper: output encoding stays the job of `escapeHtml` at the point of use.
 * The goal is narrower — make sure the string that reaches a staff member's
 * inbox, the dashboard, or a spreadsheet is the string the citizen typed, and
 * can't be dressed up to look like something else.
 */

/**
 * C0/C1 control characters, minus the whitespace we handle deliberately
 * (\t \n \r). A NUL or an ESC in a name has no legitimate meaning and is how
 * downstream parsers get confused about where a field ends.
 */
const CONTROL_CHARS = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F]/g;

/**
 * Bidirectional overrides and isolates. These reorder how text *renders*
 * without changing its bytes, so `report\u202Egnp.exe` displays as
 * `reportexe.gnp` — the classic trick for making a payload look benign in a
 * staff member's mail client. Nothing typed legitimately into these forms
 * needs them: Arabic and Hebrew render right-to-left from their own character
 * properties, which is why the site works with `dir="rtl"` and no overrides.
 */
const BIDI_CONTROLS = /[\u200E\u200F\u202A-\u202E\u2066-\u2069]/g;

/**
 * Invisible characters that pad a string without showing anything: zero-width
 * space, word joiner, byte-order mark, soft hyphen.
 *
 * Zero-width joiner/non-joiner (U+200C/U+200D) are deliberately NOT here —
 * they carry real meaning in Arabic and Persian script and hold multi-part
 * emoji together, so stripping them would corrupt legitimate submissions.
 */
const INVISIBLE_CHARS = /[\u200B\u2060\uFEFF\u00AD]/g;

/** Runs of combining marks, used to smear text over the surrounding UI. */
const EXCESSIVE_MARKS = /(\p{M})\p{M}{3,}/gu;

function stripUnsafe(input: string): string {
  return input
    .replace(CONTROL_CHARS, "")
    .replace(BIDI_CONTROLS, "")
    .replace(INVISIBLE_CHARS, "")
    .replace(EXCESSIVE_MARKS, "$1");
}

/**
 * Single-line field (name, phone, contact, reference).
 *
 * NFKC folds the compatibility forms — fullwidth Latin, Arabic presentation
 * forms, styled-maths letters — down to their plain equivalents, so two names
 * that look identical normalise identically and can't be used to smuggle a
 * lookalike past a human reader. All whitespace, newlines included, collapses
 * to single spaces.
 */
export function sanitizeLine(input: unknown, maxLength: number): string {
  if (typeof input !== "string") return "";
  return stripUnsafe(input.normalize("NFKC"))
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, maxLength);
}

/**
 * Multi-line field (message, description).
 *
 * NFC rather than NFKC: this is prose, and compatibility folding would rewrite
 * characters the citizen chose on purpose. Newlines survive, but runs of blank
 * lines and horizontal whitespace are collapsed so a submission can't be
 * padded into an unreadable wall.
 */
export function sanitizeMultiline(input: unknown, maxLength: number): string {
  if (typeof input !== "string") return "";
  return stripUnsafe(input.normalize("NFC"))
    .replace(/\r\n?/g, "\n")
    .replace(/[^\S\n]+/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .split("\n")
    .map((line) => line.trim())
    .join("\n")
    .trim()
    .slice(0, maxLength);
}

/**
 * Digits, and the punctuation people actually write phone numbers with. Any
 * other character is dropped rather than rejected, so a citizen typing
 * "+961 6 123 456 (home)" isn't blocked over the note at the end.
 */
export function sanitizePhone(input: unknown, maxLength: number): string {
  if (typeof input !== "string") return "";
  return input
    .normalize("NFKC")
    .replace(/[^\d+()\-\s]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, maxLength);
}

/** How many digits a string contains — the real test of a usable phone number. */
export function digitCount(input: string): number {
  return (input.match(/\d/g) ?? []).length;
}

/**
 * Tracking references are generated by us or by the dashboard and are always
 * alphanumeric with dashes, so anything else is noise or an injection attempt.
 * Upper-cased so a citizen retyping their code in lowercase still matches.
 */
export function sanitizeReference(input: unknown, maxLength: number): string {
  if (typeof input !== "string") return "";
  return input
    .normalize("NFKC")
    .replace(/[^A-Za-z0-9-]/g, "")
    .toUpperCase()
    .slice(0, maxLength);
}

/**
 * Bounded so the pattern can't be walked into quadratic backtracking: both
 * sides are explicitly length-capped rather than left as open `+` runs.
 */
const EMAIL_PATTERN = /^[^\s@<>,;:"'\\]{1,64}@[A-Za-z0-9.-]{1,190}\.[A-Za-z]{2,24}$/;

export function isEmailAddress(value: string): boolean {
  return value.length <= 254 && EMAIL_PATTERN.test(value);
}
